Add unit tests, tox, and GitHub Actions to run them
cfpb/cfgov-django-setup pull request #2
Opened 2019-11-08 14:13 UTC by willbarton

This PR adds unit tests for cfgov-django-setup and adds tox to run them. It also adds a GitHub Actions workflow to run the tests and a workflow to submit a new release to PyPI (based on [the same workflows in Django-Flags](https://github.com/cfpb/django-flags/tree/master/.github/workflows).

It also reorganizes `cfgov_setup` as a Python package instead of simply a module. This is mostly for name-spacing of the tests and consistency with our other Python packages.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

2019-11-13 22:44 UTC, Scotchester commented
> Code follows the standards laid out in the front end playbook

Heh, need to update this PR template.

2019-11-14 23:25 UTC, Scotchester approved these changes
Works for me! One question about import sorting.

2019-11-14 23:25 UTC, Scotchester commented on setup.py
> +from setuptools import setup, find_packages
Shouldn't isort be requiring these imports to be alphabetical?

```suggestion
from setuptools import find_packages, setup
```

2019-11-15 00:29 UTC, Scotchester commented on setup.py
> +from setuptools import setup, find_packages
Ah, maybe this warning is the issue:

```
lint run-test: commands[1] | isort --check-only --diff cfgov_setup
WARNING: Unable to parse file cfgov_setup due to [Errno 21] Is a directory: '/Users/cranfills/Projects/cfgov-django-setup/cfgov_setup'
```

2019-11-15 00:42 UTC, Scotchester requested changes

2019-11-15 00:42 UTC, Scotchester commented on tox.ini
> +    isort --check-only --diff cfgov_setup
This should do the trick:

```suggestion
    isort --check-only --diff --recursive cfgov_setup
```

2019-11-15 00:42 UTC, Scotchester commented on cfgov_setup/tests.py
> +from distutils.tests import support
With the default isort configuration, you need this:

```diff
 import unittest
+from distutils.tests import support

 from mock import patch
-from distutils.tests import support
```

2019-11-20 17:24 UTC, willbarton commented
@Scotchester thanks for catching the `isort` stuff! Ready for re-review.

2019-11-20 17:27 UTC, Scotchester approved these changes
Lookin' good!

2019-11-20 17:30 UTC, willbarton commented
I'm going to merge this as-is with the failing GitHub Actions. GitHub is aware of our issue with GitHub Actions. If a fix is not forth-coming, we can switch this repo to Travis, but we've decided to keep the Actions for now.

2019-11-20 17:32 UTC, merged